"""DEPRECATED: v1 quality-report renderer (replaced by prepare_data_v2).

``scripts/prepare_data_v2.py`` writes ``docs/DATA_QUALITY_REPORT.md`` from the
v2 manifest (per-category dedup counters, active target tokens, padding ratios,
contamination verdicts).  This module rendered the v1 manifest shape, whose
stage names and counters no longer exist.
"""
from __future__ import annotations

import warnings
from pathlib import Path
from typing import Any

MESSAGE = ("src.data.quality_report is retired; docs/DATA_QUALITY_REPORT.md is generated by "
           "scripts/prepare_data_v2.py from the v2 manifest.")


def write_quality_report(manifest: dict[str, Any], path: str | Path) -> None:
    warnings.warn(MESSAGE, DeprecationWarning, stacklevel=2)
    raise RuntimeError(MESSAGE)
